[package]
name = "mailponder"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
imap = "2.4.1"
native-tls = "0.2.12"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
log = "0.4.22"
oauth2 = "4.4.2"
url = "2.5.2"
